# Generated by Django 4.2.7 on 2023-11-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.TextField(default='Seu valor padrão aqui', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='Seu valor padrao', max_length=50),
            preserve_default=False,
        ),
    ]
